### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [koyunkyung/us_election_2024#1]
- "Kamala Harris Rises" - no. Please be specific.
- "How Poll Aggregation Reveals US Presidental Race Trends". This subtitle is damaging your credibility. Be specific and precise.
- Abstract - what is your finding? One specific sentence please.
- Tables 1 and 2 - too many decimal places.
- Captions are not informative enough.
- Reference - R packages capitalization is wrong. See starter folder example for how to use {{}} to fix this.

**Comment by koyunkyung** [comment]
Thank you so much for taking your precious time to read through and review my repo. As you commented, I modified the tables/graphs to be more comprehensible, and the abstract and title also so that the main results of the paper could be conveyed to the reader in a more informative and concrete way.
