### ISSUE TITLE
Peer Review from Kevin Roe (Group 22)

### ISSUE THREAD

**Issue by Kanghyunroe** [koyunkyung/us_election_2024#3]
### Summary
This paper examines polling data from FiveThirtyEight concerning the 2024 U.S presidential election, focusing on support trends for Donald Trump and Kamala Harris. It investigates various variables such as percentage of support,  region, time, and pollster on determining each candidate's polling numbers. This study highlights the importance of swing states and pollsters that accounted for various differences. 

### Strong Positive Points
- Clear Objective and Abstract: The Paper is well outlined and the abstract is succinct, outlining the intent and results of the study clearly
- Great job of using reputable sources such as FiveThrityEight and adequately describing the context for the analysis
- Great job including summary statistics for each variable and including model diagnostics

### Critical Improvements Needed
- Please add more commentary to the results section

### Suggestions for Improvement
- I think the overall formatting of the figures need work. Right now the figures and text are spilling over the page and some of the graphs have gridlines, which I believe isn't best practice most of the time. Add new pages when necessary
- Please work on your prose. There are certain sections in your discussion that read a bit awkwardly, so make sure to keep your writing succinct, especially because your paper is on the longer end 
- Make sure to modify the Data section to use the most recent data - there is currently a placeholder so make sure to delete it for your final project 
- Make sure to outline your final results in your appendix rather than state the objective of the paper 

### Evaluation Based on Rubric:
R is appropriately cited (1 pts):
1/1: R is appropriately referenced both in the main content and in the reference list.
Data are appropriately cited (1 pts):
1/1: The data source from FiveThirtyEight is clearly cited in the text and reference list.
Class paper (1 pts):
1/1: No visible indication that this is a class project.
LLM usage documented (1 pts):
1/1: LMM Documented
Title (2 pts):
2/2: The title is informative and clear, explaining both the focus and the context of the study.
Author, date, and repo (2 pts):
2/2: The author, date of submission, and GitHub repo link are included.
Abstract (4 pts):
3/4: The abstract explains what was done but the results could be better explained
Introduction (4 pts):
4/4: The introduction is clear and provides necessary context
Estimand (1 pts):
1/1: The estimand is defined in its own paragraph but make it a bit clearer
Data (10 pts):
8/10: The data is described well and summary statistics are included
Measurement (4 pts):
4/4: The measurement section is very thorough 
Model (10 pts):
10/10: The model is complete and has diagnostics in appendix.
Results (10 pts):
4/10: The results section is incomplete rather than highlighting the table
Discussion (10 pts):
8/10: The discussion section can be a bit more succinct
Prose (6 pts):
4/6: The prose is generally clear, but there are some minor issues with clarity, and irrelevant sections detract from the paper.
Cross-references (1 pts):
1/1: Cross-references are okay, and captions clearly explain the figures.
Captions (2 pts):
1/2: Some captions are unclear or irrelevant.
Graphs/tables/etc (4 pts):
1/4: The included graphs are irrelevant to the topic and should be replaced with more appropriate visualizations.
Idealized methodology (10 pts):
10/10: Idealized methodology well-written.
Idealized survey (4 pts):
4/4: Survey included
Pollster methodology overview and evaluation (10 pts):
10/10: Pollster methodology complete and robust
Referencing (4 pts):
4/4: References all complete
Commits (2 pts):
2/2: Various commits with meaningful messages
Sketches (2 pts):
2/2: The paper does have sketches.
Simulation (4 pts):
3/4: The paper has simulations
Tests - simulation (4 pts):
3/4: The paper has simulation tests.
Tests - actual (4 pts):
3/4: The paper has simulation tests on the actual data.
Parquet (1 pts):
1/1: The paper does not involve saving data in a parquet file.
Reproducible workflow (4 pts):
4/4: The workflow is organized, but more documentation is needed.
Miscellaneous (3 pts):
1/3: 
Estimated overall mark:
104 out of 126.

### Any other comments:
The paper is in a great spot for a first draft but definitely needs to make sure to build out the discussion and results section. There are a few placeholders that need to be deleted for the final product!

**Comment by koyunkyung** [comment]
Thank you so much for taking your precious time to read and review my paper and repo. Following your feedback, I revised the table and graphs so that they could be appropriately attached to the paper, and also reviewed the prose again.
