### ISSUE TITLE
Peer View by Max Li from Group 25

### ISSUE THREAD

**Issue by ShaotongLi-Max** [koyunkyung/us_election_2024#4]
# Summary
This paper, titled "Kamala Harris Rises as the 2024 Election Front Runner: A Poll-of-Polls Forecast", analyzes and predicts Kamala Harris's level of support in the 2024 U.S. presidential election. The authors use poll data aggregated from FiveThirtyEight, applying both linear and Bayesian models to forecast Harris’s chances of winning. The focus is on accounting for pollster-specific and state-level variability to make reliable predictions. The results indicate that Harris's support has remained stable, but the paper also highlights the variability between different pollsters and states.

# Strong Positive Points

## Methodological clarity: 
The paper effectively applies a well-explained linear and Bayesian modeling framework, making it clear how variations are accounted for in pollster and state-level differences.

## Use of real-world data: 
Reliance on reputable sources demonstrates a strong basis for the analysis, ensuring that the conclusions are data-driven.

## Comprehensive model diagnostics: 
The inclusion of detailed diagnostics for model convergence and performance enhances the credibility of the results.

# Critical Improvements Needed

## Unclear Discussion on Results: 
While the methodology is sound, the results section lacks depth. The paper briefly mentions that Harris's polling numbers have remained stable but does not explore the implications or delve into the nuances of these findings. The discussion could benefit from a more thorough interpretation of the results and their implications for the 2024 election.

## State-Level Variability Not Fully Explored:
The section on state-level differences suggests that battleground states show significant variations. However, there is limited detail on how these variations might affect the final prediction. Expanding this part could provide a clearer picture of why these states are important and how state-level factors could shift the overall election outcome.

## Overly Technical Language Without Layperson Explanation:
While the technical details are necessary for rigor, some sections could benefit from simpler language or additional explanations for a broader audience. This is especially important when discussing Bayesian modeling, which may not be familiar to all readers.

# Suggestions for Improvement:

Consider expanding the results section to provide a more thorough analysis of Harris's support trends over time and across regions.

Provide a more in-depth discussion of battleground states and their electoral significance, supported by a visual representation of state-level variability.

Refine the introduction and conclusion to tie the technical analysis more closely to the broader political context.

Include more visualizations that compare national trends versus battleground state trends, allowing readers to visualize how regional factors play a role in election outcomes.

Clarify Bayesian model interpretations for readers unfamiliar with this approach. A brief layperson summary would make the analysis more accessible.

# Evaluation
Introduction: Clear and well-motivated, but could be more engaging.
Data: Appropriate selection and pre-processing, but the explanation of filtering criteria could be more robust.
Methodology: Strong use of models, but requires clearer justifications in certain areas.
Discussion: Needs expansion, particularly on state-level variations and implications for Harris's support.
Conclusion: Lacks synthesis and strong takeaway points.

# Estimated Overall Mark
95 out of 100.

# Any Other Comments
The paper presents a well-executed analysis but falls short in fully interpreting and discussing the results. A more in-depth exploration of state-level differences and a clearer connection to real-world political implications would improve its impact.

**Comment by koyunkyung** [comment]
Thank you so much for taking the precious time to review my paper and repo. Following your feedback, I supplemented the contents of the discussion and result section, and tried to enrich the interpretation of state-level impact in particular.
