### ISSUE TITLE
Peer Review from Kevin Shen (Group 36)

### ISSUE THREAD

**Issue by kevinzshen** [koyunkyung/us_election_2024#5]
### Summary
This paper presents an analysis of polling data to predict support levels for Kamala Harris in the 2024 US presidential election using poll aggregation methods. The research utilizes polling data from FiveThirtyEight, and employs both linear and Bayesian hierarchical models to analyze polling trends. The key findings suggest that Harris's support remains relatively stable around 47%, though there are significant variations between pollsters and across states, with battleground states showing notably different polling patterns compared to national trends.

### Strong positive points:
- Informative and engaging title
- Includes thorough coverage of their sampling approach, data collection methods, and potential biases
- Identifies potential weaknesses of the model and includes suggestions on how it can be improved in the future, e.g. the inclusion of interaction terms between pollster and state and the potential inclusion of additional variables such as details about the voter demographic like age, gender, etc.

### Critical improvements needed:
- The estimand is not clearly stated in the introduction - what exactly is being estimated needs to be explicit.
- The Results section needs substantial development - currently it only references tables without meaningful discussion of findings.
- The Data section discusses removing low-quality polls but doesn't clearly justify the 2.7 threshold chosen or explain how this affects the analysis. The threshold is seemingly arbitrarily set.
- The introduction lacks a clear explanation of the gap being filled by this research and why this analysis matters.
- The model validation details in Appendix C need to be better integrated with the main text to justify model choices.

### Suggestions for improvement:
- Strengthen the statistical analysis by clarifying the progression from simple linear models to complex Bayesian models and interpreting their comparative performance.
- Address quality control issues like consistent figure formatting (proper axis labels and titles) and reference checking.
- Address potential sampling biases more thoroughly
- Include a discussion of how missing data was handled is needed

### Evaluation:
- R is appropriately cited: 1/1 - R and its packages properly referenced in text and bibliography 
- Data are appropriately cited: 1/1 - FiveThirtyEight data source clearly cited and referenced Class paper: 1/1 - No indicators this is a class assignment 
- LLM usage is documented: 1/1 - Chat logs are included in usage.txt
- Title: 2/2 - Engaging and informative subtitle about findings and contribution 
- Author, date, and repo: 2/2 - Clear author attribution, date format, and link included Abstract: 0/4 - Missing entirely, needs to be added 
- Introduction: 2/4 - Has basic structure but missing clear research gap and significance 
- Estimand: 0/1 - Not clearly stated in introduction
- Data: 6/10 - Good basic coverage but needs better justification of filtering choices and more thorough variable examination 
- Measurement: 2/4 - Basic measurement discussion present but needs more detail on how polling data was collected and processed
- Model: 6/10 - Framework present but needs better justification of modeling choices and assumptions 
- Results: 4/10 - Very limited presentation and discussion of findings 
- Discussion: 6/10 - Contains key points but needs more depth and implications 
- Prose: 4/6 - Writing is generally clear but contains some technical terms that need explanation 
- Cross-references: 1/1 - All figures, tables and equations properly numbered and referenced 
- Captions: 1/2 - Captions present but need more detailed explanations of figures/tables Graphs/tables/etc: 2/4 - Basic visualizations present but need better formatting and clearer presentation 
- Idealized methodology: 6/10 - Good framework but needs more detail about implementation and budget allocation 
- Idealized survey: 2/4 - Survey included but needs better structure and clearer question ordering 
- Pollster methodology: 8/10 - Strong detailed analysis of NYT/Siena methodology and approach
- Referencing: 3/4 - Generally well done with minor formatting inconsistencies 
- Commits: 2/2 - Many commits paired with reasonably informative commit messages
- Sketches: 2/2 - Well drawn and neatly done sketches included in the repo
- Simulation: 3/4 - The script is structured and well commented 
- Tests-simulation: 3/4 - High quality tests were written for the simulated dataset
- Tests-actual: 3/4 - High quality tests were written for the actual dataset
- Parquet: 0/1 - Analysis data is saved as a .csv instead of a parquet file
- Reproducible workflow: 3/4 - Well-structured repo with solid documentation
- Miscellaneous: 0/3 - No exceptional elements noted that go beyond rubric requirements

### Estimated overall mark:
77/126

#### Any other comments:
Overall, a good start to the paper. By completing the missing parts along with a bit of refinement, this can be a strong paper.

**Comment by koyunkyung** [comment]
Thank you so much for taking the precious time to read and review my thesis and repo. Following your feedback, I supplemented the data and results section with more detail and also added an explanation for the progress from a linear to a Bayesian model.
