### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [koyunkyung/us_election_2024#6]
- R is appropriately cited (1/1)
	- Done.
- Data are appropriately cited (1/1)
	- Done.
- Class paper (1/1)
	- Done.
- LLM usage is documented (1/1)
	- Done.
- Title (1/2)
	- Too long. Be more concise.
	- 50.03% is a weird specificity.
- Author, date, and repo (2/2)
	- Good.
- Abstract (3/4)
	- Be more concise and direct.
- Introduction (3/4)
	- Be more concise and direct.
- Estimand (0/1)
	- Could not find this.
- Data (6/10)
	- Reduce the binwidth in figure 2 - be more specific.
	- I don't understand how pollscore is created.
- Measurement (1/4)
	- Very generic ATM. For instance, where does the grade of 2.7 come from? 
	- The measurement issue is that you are trying to convert an opinion in someone's head into a number into a prediction for who will win. How this is done does not come through in your paper yet.
- Model (7/10)
	- What does a "strong inference engine" mean? Did you write that?
- Results (6/10)
	- Why not consider some graphs of the model estimates?
- Discussion (7/10)
	- Some interesting points raised.
- Prose (3/6)
	- proportion(%) needs a space.
- Cross-references (1/1)
	- Good.
- Captions (2/2)
	- Nice.
- Graphs/tables/etc (3/4)
	- Figures 12 and 13 need alpha.
- Idealized methodology (5/10)
	- Does not demonstrate your knowledge of surveys and sampling - please consider some of the papers that you've read in pre-reqs and link concepts that we've covered here.
- Idealized survey (2/4)
	- In the last question it's weird to make 1 "Likely to vote" and 10 "Not likely to vote" - flip them around.
- Pollster methodology overview and evaluation (5/10)
	- Same comment as for Idealized methodology
- Referencing (0/4)
	- "Board, The New York Times Editorial", "Center, Pew Research" and others
- Commits (2/2)
	- Great
- Sketches (2/2)
	- Great
- Simulation (3/4)
	- Fine
- Tests-simulation (3/4)
	- Fine
- Tests-actual (3/4)
	- Fine
- Parquet (0/1)
	- Not done.
- Reproducible workflow (3/4)
	- Dates in R script comments not when the script was last updated.
- Miscellaneous (2/3)
	- Figures 9 and 10 are great ideas.
	- Figure 11 is original.

**Comment by koyunkyung** [comment]
Thank you so much for taking the time to review my paper and give valuable feedbacks. I read all the comments thoroughly and tried to revise those parts as perfectly as possible.
